version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.10-bionic
      - image: quay.io/coreos/etcd:v3.3
    working_directory: /go/src/github.com/cybozu-go/etcdutil
    steps:
      - checkout
      # TODO use go mod
      - run: go get -v -t -d ./...
      - run: (cd /go/src/github.com/coreos/etcd; git checkout v3.3.9)
      - run: go get -v -t -d ./...
      - run: test -z "$(goimports -d . | tee /dev/stderr)"
      - run: golint -set_exit_status ./...
      - run: go build ./...
      - run: go test -race -v ./...
