name: main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build etcdutil
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: docker run -d --network host quay.io/coreos/etcd:v3.5.7
      - run: make setup
      - run: make check-generate
      - run: make test
