name: main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build etcdutil
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: docker run -d --network host quay.io/coreos/etcd:v3.5.10
      - run: make setup
      - run: make check-generate
      - run: make test
